# Generated by Django 2.1.7 on 2019-03-10 06:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        CreateExtension('postgis'),

        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('date', models.DateTimeField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTimeLabel', models.DateTimeField()),
                ('g1', models.IntegerField()),
                ('L', models.IntegerField()),
                ('T', models.CharField(max_length=200)),
                ('BAT', models.IntegerField()),
                ('ACC', models.CharField(max_length=200)),
                ('G4', models.CharField(max_length=200)),
                ('GPS', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('dist', models.FloatField(null=True)),
                ('TEMP', models.FloatField()),
                ('CO', models.FloatField()),
                ('NO2', models.FloatField()),
                ('fileInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress_worker.FileInfo')),
            ],
        ),
    ]
